// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbWRxaEuRDcgu8paWGVEbo7Q4e5VJ44I0',
    appId: '1:106919205476:web:160c3c054b107df795dd71',
    messagingSenderId: '106919205476',
    projectId: 'storage-app-2a962',
    authDomain: 'storage-app-2a962.firebaseapp.com',
    storageBucket: 'storage-app-2a962.appspot.com',
    measurementId: 'G-EQRBVG5276',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFHVaNv7bEoxXK5pNwLNJ-zDxUKG-yfKo',
    appId: '1:106919205476:android:2bfb310ef409379795dd71',
    messagingSenderId: '106919205476',
    projectId: 'storage-app-2a962',
    storageBucket: 'storage-app-2a962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBsk8XB8eh4GRvvFaqW47Zm0tAa9YaPw',
    appId: '1:106919205476:ios:9a8e509d039b34f795dd71',
    messagingSenderId: '106919205476',
    projectId: 'storage-app-2a962',
    storageBucket: 'storage-app-2a962.appspot.com',
    iosBundleId: 'com.example.storageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBsk8XB8eh4GRvvFaqW47Zm0tAa9YaPw',
    appId: '1:106919205476:ios:9a8e509d039b34f795dd71',
    messagingSenderId: '106919205476',
    projectId: 'storage-app-2a962',
    storageBucket: 'storage-app-2a962.appspot.com',
    iosBundleId: 'com.example.storageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbWRxaEuRDcgu8paWGVEbo7Q4e5VJ44I0',
    appId: '1:106919205476:web:3e868d9bb4274e2c95dd71',
    messagingSenderId: '106919205476',
    projectId: 'storage-app-2a962',
    authDomain: 'storage-app-2a962.firebaseapp.com',
    storageBucket: 'storage-app-2a962.appspot.com',
    measurementId: 'G-7BHZBE8N4V',
  );
}
